### ISSUE TITLE
Lazy<T>.asSequence returns infinite sequence

### ISSUE THREAD

**Issue by ilya-g** [IvanMwiruki/30-seconds-of-kotlin#1]
`asSequence` for `Lazy` being implemented this way
```
fun <T> Lazy<T>.asSequence(): Sequence<T> = object : Iterator<T> {
        override fun hasNext(): Boolean = true
        override fun next(): T = value
    }.asSequence()
```
returns a sequence that can be iterated only once, and once iterated it returns the value indefinitely, because `hasNext` is always `true`.

The correct implementation would be:
```
fun <T> Lazy<T>.asSequence(): Sequence<T> = sequence { yield(value) }
```

**Comment by ivan-moto** [comment]
The original implementation is actually what I intended: an infinite sequence of the given Lazy’s value. But now that you mention it, other people reading that snippet will likely have the same expectation you have: that the function returns a single value Sequence. Thanks for bringing this to my attention. I will update it.

**Comment by ivan-moto** [comment]
I fixed that here: https://github.com/IvanMwiruki/30-seconds-of-kotlin/commit/c99437ab0fbb25571d2736f78d682a0b70100726

Thanks again.
