### ISSUE TITLE
Question/Proposal: Use snippets inside 30 Seconds of Knowledge

### ISSUE THREAD

**Issue by petrovicstefanrs** [IvanMwiruki/30-seconds-of-kotlin#2]
Hey @IvanMwiruki, I've gotten a request on my project [30SecondsOfKnowledge](https://github.com/petrovicstefanrs/30_seconds_of_knowledge) to add your Kotlin snippets as one more library inside the extension. 

So I'm asking for permission here. Of course I'll backlink to this repo from the Readme on my repo and also put you as one of the notable contributors. If this is okay with you please let me know so I can start working on it. 

If not, that's also cool so no pressure no sweat 😄🚀

**Comment by ivan-moto** [comment]
Hey @petrovicstefanrs. I ran across your 30 seconds of knowledge project a few months ago and was actually considering reaching out to you. I would love for 30 seconds of Kotlin to be included. Please let me know if there's anything else you need from my end.

**Comment by ivan-moto** [comment]
I also added your project to `Related projects` in this repo: https://github.com/IvanMwiruki/30-seconds-of-kotlin/commit/675853eff080551da46777e9c9f3e35dded19ceb

**Comment by petrovicstefanrs** [comment]
@IvanMwiruki Hhehe nice, it's a deal then I will start implementing your snippets into 30SoK. It would be great if you could generate individual snippet md files for each snippet, as I see you are generating the Readme dynamically. If you however don't have the time or the will to do it it's not a biggie I'll start gradually extracting the snippets you have now 😄

**Comment by ivan-moto** [comment]
I’m doing way worse then dynamically generating the readme. Right now, the readme is hand written. I have plans to put the snippets in individual files and generate the readme but I’m not sure when I’ll get to that. 

Thanks again. I’m going to resolve this.
